export const Types = {
    GET_BOOKS: 'GET_BOOKS',
    GET_BOOK: 'GET_BOOK',
    ADD_BOOK: 'ADD_BOOK',
    REMOVE_BOOK: 'REMOVE_BOOK',
    UPDATE_BOOK: 'UPDATE_BOOK',
    ADD_BOOK_FILTER: 'ADD_BOOK_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
